export const PAKISTANI_BANKS = [
  "JazzCash",
  "EasyPaisa",
  "SadaPay",
  "NayaPay",
  "Zindigi",
  "HBL Konnect",
  "UPaisa",
  "OneZapp",

  "HBL (Habib Bank Limited)",
  "UBL (United Bank Limited)",
  "MCB Bank Limited",
  "Allied Bank Limited",
  "Meezan Bank Limited",
  "Bank Alfalah",
  "Standard Chartered Bank Pakistan",
  "Askari Bank",
  "Bank Al Habib",
  "Faysal Bank",
  "Habib Metropolitan Bank",
  "The Bank of Punjab",
  "The Bank of Khyber",
  "JS Bank",
  "Soneri Bank",
  "Al Baraka Bank",
  "Summit Bank",
  "Silkbank",
  "Sindh Bank",
  "National Bank of Pakistan (NBP)",
  "Dubai Islamic Bank",
  "BankIslami Pakistan Limited",
  "First Women Bank Limited",
  "Zarai Taraqiati Bank Limited (ZTBL)",
  "Bank Makramah Limited",
  "Mashreq Bank Pakistan",
  "Citibank Pakistan",
  "Deutsche Bank Pakistan",
  "Industrial and Commercial Bank of China (ICBC)",
  "Bank of China Pakistan",
];
